import "./globals.css";
import StoreProvider from "./StoreProvider";

export const metadata = {
  title: "Managing graduation",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StoreProvider>
        <body suppressHydrationWarning={true}>{children}</body>
      </StoreProvider>
    </html>
  );
}
